trigger:
- main

pool:
  name: DSO

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
- task: FortifyScanCentralSAST@7
  inputs:
    scanCentralCtrlUrl: 'https://192.168.243.129:8085/scancentral-ctrl/'
    scanCentralClientToken: '$(ScanCentral.ClientToken)'
    sscUrl: 'https://192.168.243.129:8084/ssc/'
    sscCiToken: '$(ScanCentral.SscCiToken)'
    uploadToSSC: true
    applicationName: 'test'
    applicationVersion: 'test'
    autoDetectBuildTool: true
  displayName: 'Run a multi-line script'